#+title: Planning

* Intro Speech

- Nolan
- I'll be arranging SI for Professor Susman this semester.
- I'm also an ACC student, Computer Science, and I took this course, with Professor Susman, in FALL 2021.
- Personally, I am fairly strong with CS and C++

- The goal of these SI sessions is to get you all working together on problems and collaborating to find solution. The biggest resouces I've gotten from my computer science (and other classes) is the connections with fellow students that I've made, where we can share and build upon ideas.
- I hope, too, outside of the course curriculum, I can share some of my passion for CS and point you all in the direction of some of the great CS resources that I've found along the way -- things that make programming both easier and more fun.

- They are not manditory, but really recommended. The college has data that shows students who have participated in SI, on average, achieve a grade-point higher than those who don't.

- Early on in the semester you might have little challenge with the material, but very quickly we will move into complicated and abstract things -- like pointers and memory allocation -- that you will have to have down perfectly before moving on to Fundamentals III, which assumes you are solid with.

- I'll have a info letter to send out with a little more detail, along with a survery regarding when would be the best time, with your schedules, to hold these sessions.

* First Day Objectives

- ICE BREAKING ACTIVITY
- Get a sense of where they're at with CS overall
- Configuring Editors
- Work on covered material
- Look ahead to upcoming material (possibly)
- CLOSING ACTIVITY

* ACTIVITY Ideas

- Write the program
  Given a problem, write the (short) program.
  + _
- [[./challenges/find-the-bug.org][Find the bug]]
  Given a program, find the error(s).
  + They solve mine
  + They share their's with eachother
  + I show them my process, solving theirs
- Build a process map (graphviz)
  +

* General Goals

- help learn material
- assist collaboration
- guide them towards best-practices
- hint at tools and utilites to get the job done (and excite with possibilities)
