#+title: Find The Bug(s)

Try your best to solve them without running the code, especially for the earlier challenges.

Once you think you have an answer, fix it an run.
- if its still broken, try to parse the error.
- if it worked, re-break the program, explain what the error might be, then run and read the error log to match up your understanding.

* Contents :toc:
- [[#section-1][Section 1]]
  - [[#challenge-0][Challenge 0]]
  - [[#challenge-1][Challenge 1]]
  - [[#challenge-2][Challenge 2]]
  - [[#challenge-3][Challenge 3]]
- [[#section-2][Section 2]]
  - [[#challenge-0-1][Challenge 0]]
  - [[#challenge-1-1][Challenge 1]]
  - [[#challenge-2-1][Challenge 2]]
- [[#section-3][Section 3]]
  - [[#challenge-0-2][Challenge 0]]
  - [[#challenge-1-2][Challenge 1]]

* Section 1
** Challenge 0

Bugs: 1

#+begin_src C++ :main no :results output
#include <iostream> // for cout

std::cout << "Hello, World!" << '\n';
#+end_src

** Challenge 1

Bugs: 1

#+begin_src C++ :results output
include <iostream> // for cout

int main()
{
    std::cout << "Hello, World!" << '\n';
    return 0;
}
#+end_src

** Challenge 2

Bugs: 1

#+begin_src C++ :results output
#include <iostream> // for cout

int main()
{
    std::cout >> "Hello, World!" >> '\n';
    return 0;
}
#+end_src

** Challenge 3

Bugs: 1

#+begin_src C++ :results output
#include <iostream> // for cout

int main()
{
    cout << "Hello, World!" << '\n';
    return 0;
}
#+end_src

* Section 2
** Challenge 0

#+begin_src C++
#include <iostream>

int main()
{
    std::cout << "Hello, World!" << '\n';

    return 0;
}
#+end_src

** Challenge 1

Not returning from an int main function.

#+begin_src C++
#include <iostream>

int main()
{
    std::cout << "Hello, World!" << '\n';
}
#+end_src

** Challenge 2

Returning 0 in a void main function.

#+begin_src C++
#include <iostream>

void main()
{
    std::cout << "Hello, World!" << '\n';

    return 0;
}
#+end_src

#+RESULTS:
* TODO Section 3
** Challenge 0

#+begin_src C++
int main() {

    return 0;
}
#+end_src

** Challenge 1
